### ISSUE TITLE
Implement SourceKit-LSP

### ISSUE THREAD

**Issue by tonycoco** [zed-extensions/swift#5]
Adding LSP support would make this more fully featured.

https://github.com/apple/sourcekit-lsp

**Comment by tonycoco** [comment]
See also: https://github.com/zed-industries/zed/issues/7096

**Comment by furby-tm** [comment]
I'm also quite interested in using **Zed**, but sadly due to lacking an integration with Swift's [**SourceKit-LSP**](https://github.com/apple/sourcekit-lsp) it renders the text editor completely useless to me 😅.

I'd love to help out with this, if it means we can see an integration with **SourceKit-LSP** that much sooner.

Thanks!

**Comment by louisnicolas-longheval-vinci** [comment]
> I'm also quite interested in using **Zed**, but sadly due to lacking an integration with Swift's [**SourceKit-LSP**](https://github.com/apple/sourcekit-lsp) it renders the text editor completely useless for me 😅.
> 
> I'd love to help out with this, if it means we can see an integration with **SourceKit-LSP** that much sooner.
> 
> I'm unsure the difference between **_"baked in"_** plugins vs. external plugins (such as this one), but got something very minimally working with **SourceKit-LSP** using a **_"baked in"_** approach [here](https://github.com/wabiverse/zed/commit/d180aa511da326e1193536a5246f233c6954b03d).
> 
> Tip
> 
> I fudged up on that initial attempt, but corrected it [here](https://github.com/wabiverse/zed/commit/a98bf9fd32c92bc76d0eb31d2457ff211ceda9ec).
> 
> Thanks!

Hi, for the moment i don't have the time to understand and integrate the LSP. In addition i'm not too familiar with it... So if you would like to add it to this repo feel free to fork it and create a PR!

**Comment by evrsen** [comment]
> Hi, for the moment i don't have the time to understand and integrate the LSP. In addition i'm not too familiar with it... So if you would like to add it to this repo feel free to fork it and create a PR!

Hi, have you considered transferring ownership of the repository to someone who have the time to maintain this extension? You could alternatively transfer it to @zed-extensions which is what I did with the Kotlin extension https://github.com/zed-extensions/zed-kotlin/issues/1

**Comment by tonycoco** [comment]
Would be ideal if the repo lived in the @zed-extensions. I can also help here. @evrsen your changes look good to me. Pretty straight forward.

**Comment by louisnicolas-longheval-vinci** [comment]
@evrsen I don't really know the process to transfer it, could you guide me like you did for your extension?

**Comment by WeetHet** [comment]
> @evrsen I don't really know the process to transfer it, could you guide me like you did for your extension?

There is a button in the repo settings to transfer the repository. You could try transferring it to @maxdeviant if he is okay with it and then he would transfer it to zed-extensions

**Comment by louisnicolas-longheval-vinci** [comment]
@maxdeviant would you be okay with that?

**Comment by maxdeviant** [comment]
> @maxdeviant would you be okay with that?

Yep, feel free to transfer to me and I can transfer it to the @zed-extensions org.

**Comment by ejjonny** [comment]
If anyone comes across this - I tried to get LSP working as an extension & ran into sourcekit troubles. 
Would appreciate any ideas!
Code: https://github.com/ejjonny/swift-ext
Troubles: https://github.com/zed-industries/extensions/issues/139#issuecomment-2080282984

**Comment by yaroslavyaroslav** [comment]
FYI: There's a tool to add support for iOS lsp leveraged code completion with low effort:


`buildServer.json`
```json
{
    "name": "xcode build server",
    "version": "0.2",
    "bspVersion": "2.0",
    "languages": [
        "c",
        "cpp",
        "objective-c",
        "objective-cpp",
        "swift"
    ],
    "argv": [
        "/opt/homebrew/bin/xcode-build-server"
    ],
    "indexStorePath": "/Users/user/Library/Developer/Xcode/DerivedData/TheApp-brevdtkvkmeibkbvojjivinndsjo/Index.noindex/DataStore",
    "kind": "xcode",
    "workspace": "/Users/user/Development/Work/TheApp/mobile-ios/TheApp.xcworkspace",
    "build_root": "/Users/user/Library/Developer/Xcode/DerivedData/TheApp-brevdtkvkmeibkbvojjivinndsjo",
    "scheme": "TheAppScheme"
}
```

The repo itself of a tool itself. https://github.com/SolaWing/xcode-build-server
