### ISSUE TITLE
`sourcekit-lsp` does not appear to be responding

### ISSUE THREAD

**Issue by valentinegb** [zed-extensions/swift#8]
I'm only just learning Swift so it's very possible I've missed something, but the Swift language server doesn't seem to be responding to Zed at all:

<img width="1508" alt="Screenshot 2024-06-11 at 6 15 10 PM" src="https://github.com/zed-extensions/swift/assets/35977727/848b7148-4a93-452c-8358-748e45689e38">

<img width="697" alt="Screenshot 2024-06-11 at 6 16 56 PM" src="https://github.com/zed-extensions/swift/assets/35977727/c19716d5-773b-491d-b206-c5e492aa8882">

It may be notable that I am currently on the macOS 15 beta.

**Comment by louisnicolas-longheval-vinci** [comment]
hi @valentinegb from my point of view, on macOS15beta 1 it seems to work properly... maybe @ejjonny can help you on this side with the lsp?

**Comment by ejjonny** [comment]
What do you see when you run `xcrun —find sourcekit-lsp`?

It may also be useful to check whether the vscode swift plugin works on your system to rule out the editor.

**Comment by valentinegb** [comment]
> What do you see when you run `xcrun --find sourcekit-lsp`?

```
/Library/Developer/CommandLineTools/usr/bin/sourcekit-lsp
```

> It may also be useful to check whether the vscode swift plugin works on your system to rule out the editor.

Give me a few minutes to set that up and I'll get back to you on that

**Comment by valentinegb** [comment]
Seems to be working in VSCode at least better than in Zed

![Screenshot 2024-06-12 at 12 08 32 PM](https://github.com/zed-extensions/swift/assets/35977727/b4f057a8-2488-444b-bccd-a0a38d4308ec)

![Screenshot 2024-06-12 at 12 09 54 PM](https://github.com/zed-extensions/swift/assets/35977727/043d260d-2c25-4acc-9c3e-d519efbabde5)

**Comment by valentinegb** [comment]
Update: uhhh it works now? I have no idea why, I started the language server in my terminal and it started working, but it kept working even after I stopped the server in my terminal and restarted Zed.
